server:
  port: 6200

spring:
  application:
    name: artist-search-service
  jackson:
    default-property-inclusion: NON_NULL
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      password: password
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,ready

mashup:
  artist-search-service:
    musicbranz-service:
      url: "http://musicbrainz.org/ws/2/"
      path: artist/%s?fmt=json&inc=url-rels+release-groups
      cacheName: "MUSICBRANZ"
      timeoutSeconds: 2
    coverartarchive-service:
      url: "http://coverartarchive.org/release-group"
      path: /%s
      cacheName: "COVERART"
      timeoutSeconds: 2
    discogs-service:
      url: "https://api.discogs.com/"
      path: artists/%s
      cacheName: "DISCOG"
      timeoutSeconds: 2
    throttling:
      requestPerSecond: 10
      timeout: 10
    cache:
      retention-days: 1



